-- ⚠️ APPLIED 2026-08-31 AND IMMEDIATELY REVERTED — DO NOT RUN AGAIN. ⚠️
--
-- Intent was to add Cynthia King's Saturday 8/29 re-hash appointment for
-- Grace Barnett, believed missing. Reading production proved otherwise:
-- pulse 12896954975 carries TWO Card_Outcome_Recorded markers —
--   @08-26 Ernie Ruiz  blowouts md=2026-08-26  (his Wednesday canvass run)
--   @08-29 Cynthia King blowouts md=2026-08-29 (her Saturday re-hash run)
-- so BOTH appointments were already counted, on the right days, for the
-- right people. This script's "which side is missing?" test read only the
-- LATEST marker per pulse and therefore concluded the other side was
-- absent; running it added a duplicate No Demo to Ernie on 8/26 (his
-- daily_logs.no_demo went 2 → 3 against a board truth of 2).
--
-- The revert (UPDATE-only, run 2026-08-31) decremented daily_logs.no_demo
-- and daily_metrics.blowouts back by 1 and rewrote the inserted marker to
-- step 'Card_Outcome_Reverted' with bucket NULL, so it neither counts nor
-- poisons a future transition. Verified after: Ernie 8/26 no_demo = 2.
-- Audit trail: webhook_logs step 'Manual_Correction',
-- tag 'barnett-saturday-20260831-REVERTED'.
--
-- LESSON (kept deliberately, not deleted): markers ACCUMULATE per pulse —
-- one card re-run across two days holds one marker per appointment. Never
-- infer "what the app counted" from the latest marker alone; sum the
-- counters (daily_logs / daily_metrics) for the day in question instead.
--
-- The original SQL is intentionally not preserved here: it is unsafe to
-- re-run and its only remaining value is the lesson above. The live
-- re-run handling it was meant to backfill ships in PR #131
-- (sameStateRerun) and needs no data backfill for the week of 8/24.
