/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTerritoriesRouteImport } from './routes/_authenticated/territories'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlaybookRouteImport } from './routes/_authenticated/playbook'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedMyTerritoryRouteImport } from './routes/_authenticated/my-territory'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedFieldRouteImport } from './routes/_authenticated/field'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyWrapRouteImport } from './routes/_authenticated/daily-wrap'
import { Route as AuthenticatedConfirmationDeskRouteImport } from './routes/_authenticated/confirmation-desk'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedActiveRunRouteImport } from './routes/_authenticated/active-run'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams.index'
import { Route as ApiPublicMondayWebhookRouteImport } from './routes/api/public/monday-webhook'
import { Route as ApiPublicMondayLiveDispatchRouteImport } from './routes/api/public/monday-live-dispatch'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedCanvassersCanvasserIdRouteImport } from './routes/_authenticated/canvassers.$canvasserId'
import { Route as AuthenticatedCanvassersCanvasserIdFieldRouteImport } from './routes/_authenticated/canvassers.$canvasserId.field'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTerritoriesRoute =
  AuthenticatedTerritoriesRouteImport.update({
    id: '/territories',
    path: '/territories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaybookRoute = AuthenticatedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTerritoryRoute =
  AuthenticatedMyTerritoryRouteImport.update({
    id: '/my-territory',
    path: '/my-territory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldRoute = AuthenticatedFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyWrapRoute = AuthenticatedDailyWrapRouteImport.update({
  id: '/daily-wrap',
  path: '/daily-wrap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfirmationDeskRoute =
  AuthenticatedConfirmationDeskRouteImport.update({
    id: '/confirmation-desk',
    path: '/confirmation-desk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActiveRunRoute = AuthenticatedActiveRunRouteImport.update({
  id: '/active-run',
  path: '/active-run',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMondayWebhookRoute = ApiPublicMondayWebhookRouteImport.update({
  id: '/api/public/monday-webhook',
  path: '/api/public/monday-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMondayLiveDispatchRoute =
  ApiPublicMondayLiveDispatchRouteImport.update({
    id: '/api/public/monday-live-dispatch',
    path: '/api/public/monday-live-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvassersCanvasserIdRoute =
  AuthenticatedCanvassersCanvasserIdRouteImport.update({
    id: '/canvassers/$canvasserId',
    path: '/canvassers/$canvasserId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvassersCanvasserIdFieldRoute =
  AuthenticatedCanvassersCanvasserIdFieldRouteImport.update({
    id: '/field',
    path: '/field',
    getParentRoute: () => AuthenticatedCanvassersCanvasserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/active-run': typeof AuthenticatedActiveRunRoute
  '/command': typeof AuthenticatedCommandRoute
  '/confirmation-desk': typeof AuthenticatedConfirmationDeskRoute
  '/daily-wrap': typeof AuthenticatedDailyWrapRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/field': typeof AuthenticatedFieldRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/my-territory': typeof AuthenticatedMyTerritoryRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/territories': typeof AuthenticatedTerritoriesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/canvassers/$canvasserId': typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/monday-live-dispatch': typeof ApiPublicMondayLiveDispatchRoute
  '/api/public/monday-webhook': typeof ApiPublicMondayWebhookRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/canvassers/$canvasserId/field': typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/active-run': typeof AuthenticatedActiveRunRoute
  '/command': typeof AuthenticatedCommandRoute
  '/confirmation-desk': typeof AuthenticatedConfirmationDeskRoute
  '/daily-wrap': typeof AuthenticatedDailyWrapRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/field': typeof AuthenticatedFieldRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/my-territory': typeof AuthenticatedMyTerritoryRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/territories': typeof AuthenticatedTerritoriesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/canvassers/$canvasserId': typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/monday-live-dispatch': typeof ApiPublicMondayLiveDispatchRoute
  '/api/public/monday-webhook': typeof ApiPublicMondayWebhookRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/canvassers/$canvasserId/field': typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/active-run': typeof AuthenticatedActiveRunRoute
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/confirmation-desk': typeof AuthenticatedConfirmationDeskRoute
  '/_authenticated/daily-wrap': typeof AuthenticatedDailyWrapRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/field': typeof AuthenticatedFieldRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/my-territory': typeof AuthenticatedMyTerritoryRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/playbook': typeof AuthenticatedPlaybookRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/territories': typeof AuthenticatedTerritoriesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/canvassers/$canvasserId': typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/monday-live-dispatch': typeof ApiPublicMondayLiveDispatchRoute
  '/api/public/monday-webhook': typeof ApiPublicMondayWebhookRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/canvassers/$canvasserId/field': typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/active-run'
    | '/command'
    | '/confirmation-desk'
    | '/daily-wrap'
    | '/dashboard'
    | '/dispatch'
    | '/field'
    | '/fleet'
    | '/leaderboard'
    | '/log'
    | '/my-territory'
    | '/payroll'
    | '/playbook'
    | '/settings'
    | '/territories'
    | '/users'
    | '/canvassers/$canvasserId'
    | '/teams/$teamId'
    | '/api/public/monday-live-dispatch'
    | '/api/public/monday-webhook'
    | '/teams/'
    | '/canvassers/$canvasserId/field'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/active-run'
    | '/command'
    | '/confirmation-desk'
    | '/daily-wrap'
    | '/dashboard'
    | '/dispatch'
    | '/field'
    | '/fleet'
    | '/leaderboard'
    | '/log'
    | '/my-territory'
    | '/payroll'
    | '/playbook'
    | '/settings'
    | '/territories'
    | '/users'
    | '/canvassers/$canvasserId'
    | '/teams/$teamId'
    | '/api/public/monday-live-dispatch'
    | '/api/public/monday-webhook'
    | '/teams'
    | '/canvassers/$canvasserId/field'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/active-run'
    | '/_authenticated/command'
    | '/_authenticated/confirmation-desk'
    | '/_authenticated/daily-wrap'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispatch'
    | '/_authenticated/field'
    | '/_authenticated/fleet'
    | '/_authenticated/leaderboard'
    | '/_authenticated/log'
    | '/_authenticated/my-territory'
    | '/_authenticated/payroll'
    | '/_authenticated/playbook'
    | '/_authenticated/settings'
    | '/_authenticated/territories'
    | '/_authenticated/users'
    | '/_authenticated/canvassers/$canvasserId'
    | '/_authenticated/teams/$teamId'
    | '/api/public/monday-live-dispatch'
    | '/api/public/monday-webhook'
    | '/_authenticated/teams/'
    | '/_authenticated/canvassers/$canvasserId/field'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMondayLiveDispatchRoute: typeof ApiPublicMondayLiveDispatchRoute
  ApiPublicMondayWebhookRoute: typeof ApiPublicMondayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/territories': {
      id: '/_authenticated/territories'
      path: '/territories'
      fullPath: '/territories'
      preLoaderRoute: typeof AuthenticatedTerritoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbook': {
      id: '/_authenticated/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthenticatedPlaybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-territory': {
      id: '/_authenticated/my-territory'
      path: '/my-territory'
      fullPath: '/my-territory'
      preLoaderRoute: typeof AuthenticatedMyTerritoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field': {
      id: '/_authenticated/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AuthenticatedFieldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-wrap': {
      id: '/_authenticated/daily-wrap'
      path: '/daily-wrap'
      fullPath: '/daily-wrap'
      preLoaderRoute: typeof AuthenticatedDailyWrapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirmation-desk': {
      id: '/_authenticated/confirmation-desk'
      path: '/confirmation-desk'
      fullPath: '/confirmation-desk'
      preLoaderRoute: typeof AuthenticatedConfirmationDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/active-run': {
      id: '/_authenticated/active-run'
      path: '/active-run'
      fullPath: '/active-run'
      preLoaderRoute: typeof AuthenticatedActiveRunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/monday-webhook': {
      id: '/api/public/monday-webhook'
      path: '/api/public/monday-webhook'
      fullPath: '/api/public/monday-webhook'
      preLoaderRoute: typeof ApiPublicMondayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monday-live-dispatch': {
      id: '/api/public/monday-live-dispatch'
      path: '/api/public/monday-live-dispatch'
      fullPath: '/api/public/monday-live-dispatch'
      preLoaderRoute: typeof ApiPublicMondayLiveDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvassers/$canvasserId': {
      id: '/_authenticated/canvassers/$canvasserId'
      path: '/canvassers/$canvasserId'
      fullPath: '/canvassers/$canvasserId'
      preLoaderRoute: typeof AuthenticatedCanvassersCanvasserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvassers/$canvasserId/field': {
      id: '/_authenticated/canvassers/$canvasserId/field'
      path: '/field'
      fullPath: '/canvassers/$canvasserId/field'
      preLoaderRoute: typeof AuthenticatedCanvassersCanvasserIdFieldRouteImport
      parentRoute: typeof AuthenticatedCanvassersCanvasserIdRoute
    }
  }
}

interface AuthenticatedCanvassersCanvasserIdRouteChildren {
  AuthenticatedCanvassersCanvasserIdFieldRoute: typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}

const AuthenticatedCanvassersCanvasserIdRouteChildren: AuthenticatedCanvassersCanvasserIdRouteChildren =
  {
    AuthenticatedCanvassersCanvasserIdFieldRoute:
      AuthenticatedCanvassersCanvasserIdFieldRoute,
  }

const AuthenticatedCanvassersCanvasserIdRouteWithChildren =
  AuthenticatedCanvassersCanvasserIdRoute._addFileChildren(
    AuthenticatedCanvassersCanvasserIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActiveRunRoute: typeof AuthenticatedActiveRunRoute
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedConfirmationDeskRoute: typeof AuthenticatedConfirmationDeskRoute
  AuthenticatedDailyWrapRoute: typeof AuthenticatedDailyWrapRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedFieldRoute: typeof AuthenticatedFieldRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedMyTerritoryRoute: typeof AuthenticatedMyTerritoryRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPlaybookRoute: typeof AuthenticatedPlaybookRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTerritoriesRoute: typeof AuthenticatedTerritoriesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedCanvassersCanvasserIdRoute: typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActiveRunRoute: AuthenticatedActiveRunRoute,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedConfirmationDeskRoute: AuthenticatedConfirmationDeskRoute,
  AuthenticatedDailyWrapRoute: AuthenticatedDailyWrapRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedFieldRoute: AuthenticatedFieldRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedMyTerritoryRoute: AuthenticatedMyTerritoryRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPlaybookRoute: AuthenticatedPlaybookRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTerritoriesRoute: AuthenticatedTerritoriesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedCanvassersCanvasserIdRoute:
    AuthenticatedCanvassersCanvasserIdRouteWithChildren,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMondayLiveDispatchRoute: ApiPublicMondayLiveDispatchRoute,
  ApiPublicMondayWebhookRoute: ApiPublicMondayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
