/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedPlaybookRouteImport } from './routes/_authenticated/playbook'
import { Route as AuthenticatedMyTerritoryRouteImport } from './routes/_authenticated/my-territory'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFieldRouteImport } from './routes/_authenticated/field'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyWrapRouteImport } from './routes/_authenticated/daily-wrap'
import { Route as AuthenticatedConfirmationDeskRouteImport } from './routes/_authenticated/confirmation-desk'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams.index'
import { Route as ApiPublicMondayWebhookRouteImport } from './routes/api/public/monday-webhook'
import { Route as ApiPublicMondayLiveDispatchRouteImport } from './routes/api/public/monday-live-dispatch'
import { Route as ApiInternalRotateBoardsRouteImport } from './routes/api/internal/rotate-boards'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedCanvassersCanvasserIdRouteImport } from './routes/_authenticated/canvassers.$canvasserId'
import { Route as AuthenticatedCanvassersCanvasserIdFieldRouteImport } from './routes/_authenticated/canvassers.$canvasserId.field'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaybookRoute = AuthenticatedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTerritoryRoute =
  AuthenticatedMyTerritoryRouteImport.update({
    id: '/my-territory',
    path: '/my-territory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldRoute = AuthenticatedFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyWrapRoute = AuthenticatedDailyWrapRouteImport.update({
  id: '/daily-wrap',
  path: '/daily-wrap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfirmationDeskRoute =
  AuthenticatedConfirmationDeskRouteImport.update({
    id: '/confirmation-desk',
    path: '/confirmation-desk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMondayWebhookRoute = ApiPublicMondayWebhookRouteImport.update({
  id: '/api/public/monday-webhook',
  path: '/api/public/monday-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMondayLiveDispatchRoute =
  ApiPublicMondayLiveDispatchRouteImport.update({
    id: '/api/public/monday-live-dispatch',
    path: '/api/public/monday-live-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalRotateBoardsRoute = ApiInternalRotateBoardsRouteImport.update({
  id: '/api/internal/rotate-boards',
  path: '/api/internal/rotate-boards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvassersCanvasserIdRoute =
  AuthenticatedCanvassersCanvasserIdRouteImport.update({
    id: '/canvassers/$canvasserId',
    path: '/canvassers/$canvasserId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvassersCanvasserIdFieldRoute =
  AuthenticatedCanvassersCanvasserIdFieldRouteImport.update({
    id: '/field',
    path: '/field',
    getParentRoute: () => AuthenticatedCanvassersCanvasserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirmation-desk': typeof AuthenticatedConfirmationDeskRoute
  '/daily-wrap': typeof AuthenticatedDailyWrapRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/field': typeof AuthenticatedFieldRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/my-territory': typeof AuthenticatedMyTerritoryRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/users': typeof AuthenticatedUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/canvassers/$canvasserId': typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/internal/rotate-boards': typeof ApiInternalRotateBoardsRoute
  '/api/public/monday-live-dispatch': typeof ApiPublicMondayLiveDispatchRoute
  '/api/public/monday-webhook': typeof ApiPublicMondayWebhookRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/canvassers/$canvasserId/field': typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirmation-desk': typeof AuthenticatedConfirmationDeskRoute
  '/daily-wrap': typeof AuthenticatedDailyWrapRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/field': typeof AuthenticatedFieldRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/my-territory': typeof AuthenticatedMyTerritoryRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/users': typeof AuthenticatedUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/canvassers/$canvasserId': typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/internal/rotate-boards': typeof ApiInternalRotateBoardsRoute
  '/api/public/monday-live-dispatch': typeof ApiPublicMondayLiveDispatchRoute
  '/api/public/monday-webhook': typeof ApiPublicMondayWebhookRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/canvassers/$canvasserId/field': typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/confirmation-desk': typeof AuthenticatedConfirmationDeskRoute
  '/_authenticated/daily-wrap': typeof AuthenticatedDailyWrapRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/field': typeof AuthenticatedFieldRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/my-territory': typeof AuthenticatedMyTerritoryRoute
  '/_authenticated/playbook': typeof AuthenticatedPlaybookRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/_authenticated/canvassers/$canvasserId': typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/internal/rotate-boards': typeof ApiInternalRotateBoardsRoute
  '/api/public/monday-live-dispatch': typeof ApiPublicMondayLiveDispatchRoute
  '/api/public/monday-webhook': typeof ApiPublicMondayWebhookRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/canvassers/$canvasserId/field': typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirmation-desk'
    | '/daily-wrap'
    | '/dashboard'
    | '/field'
    | '/leaderboard'
    | '/log'
    | '/my-territory'
    | '/playbook'
    | '/users'
    | '/auth/callback'
    | '/canvassers/$canvasserId'
    | '/teams/$teamId'
    | '/api/internal/rotate-boards'
    | '/api/public/monday-live-dispatch'
    | '/api/public/monday-webhook'
    | '/teams/'
    | '/canvassers/$canvasserId/field'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirmation-desk'
    | '/daily-wrap'
    | '/dashboard'
    | '/field'
    | '/leaderboard'
    | '/log'
    | '/my-territory'
    | '/playbook'
    | '/users'
    | '/auth/callback'
    | '/canvassers/$canvasserId'
    | '/teams/$teamId'
    | '/api/internal/rotate-boards'
    | '/api/public/monday-live-dispatch'
    | '/api/public/monday-webhook'
    | '/teams'
    | '/canvassers/$canvasserId/field'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/confirmation-desk'
    | '/_authenticated/daily-wrap'
    | '/_authenticated/dashboard'
    | '/_authenticated/field'
    | '/_authenticated/leaderboard'
    | '/_authenticated/log'
    | '/_authenticated/my-territory'
    | '/_authenticated/playbook'
    | '/_authenticated/users'
    | '/auth_/callback'
    | '/_authenticated/canvassers/$canvasserId'
    | '/_authenticated/teams/$teamId'
    | '/api/internal/rotate-boards'
    | '/api/public/monday-live-dispatch'
    | '/api/public/monday-webhook'
    | '/_authenticated/teams/'
    | '/_authenticated/canvassers/$canvasserId/field'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiInternalRotateBoardsRoute: typeof ApiInternalRotateBoardsRoute
  ApiPublicMondayLiveDispatchRoute: typeof ApiPublicMondayLiveDispatchRoute
  ApiPublicMondayWebhookRoute: typeof ApiPublicMondayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbook': {
      id: '/_authenticated/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthenticatedPlaybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-territory': {
      id: '/_authenticated/my-territory'
      path: '/my-territory'
      fullPath: '/my-territory'
      preLoaderRoute: typeof AuthenticatedMyTerritoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field': {
      id: '/_authenticated/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AuthenticatedFieldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-wrap': {
      id: '/_authenticated/daily-wrap'
      path: '/daily-wrap'
      fullPath: '/daily-wrap'
      preLoaderRoute: typeof AuthenticatedDailyWrapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirmation-desk': {
      id: '/_authenticated/confirmation-desk'
      path: '/confirmation-desk'
      fullPath: '/confirmation-desk'
      preLoaderRoute: typeof AuthenticatedConfirmationDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/monday-webhook': {
      id: '/api/public/monday-webhook'
      path: '/api/public/monday-webhook'
      fullPath: '/api/public/monday-webhook'
      preLoaderRoute: typeof ApiPublicMondayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monday-live-dispatch': {
      id: '/api/public/monday-live-dispatch'
      path: '/api/public/monday-live-dispatch'
      fullPath: '/api/public/monday-live-dispatch'
      preLoaderRoute: typeof ApiPublicMondayLiveDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/rotate-boards': {
      id: '/api/internal/rotate-boards'
      path: '/api/internal/rotate-boards'
      fullPath: '/api/internal/rotate-boards'
      preLoaderRoute: typeof ApiInternalRotateBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvassers/$canvasserId': {
      id: '/_authenticated/canvassers/$canvasserId'
      path: '/canvassers/$canvasserId'
      fullPath: '/canvassers/$canvasserId'
      preLoaderRoute: typeof AuthenticatedCanvassersCanvasserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvassers/$canvasserId/field': {
      id: '/_authenticated/canvassers/$canvasserId/field'
      path: '/field'
      fullPath: '/canvassers/$canvasserId/field'
      preLoaderRoute: typeof AuthenticatedCanvassersCanvasserIdFieldRouteImport
      parentRoute: typeof AuthenticatedCanvassersCanvasserIdRoute
    }
  }
}

interface AuthenticatedCanvassersCanvasserIdRouteChildren {
  AuthenticatedCanvassersCanvasserIdFieldRoute: typeof AuthenticatedCanvassersCanvasserIdFieldRoute
}

const AuthenticatedCanvassersCanvasserIdRouteChildren: AuthenticatedCanvassersCanvasserIdRouteChildren =
  {
    AuthenticatedCanvassersCanvasserIdFieldRoute:
      AuthenticatedCanvassersCanvasserIdFieldRoute,
  }

const AuthenticatedCanvassersCanvasserIdRouteWithChildren =
  AuthenticatedCanvassersCanvasserIdRoute._addFileChildren(
    AuthenticatedCanvassersCanvasserIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfirmationDeskRoute: typeof AuthenticatedConfirmationDeskRoute
  AuthenticatedDailyWrapRoute: typeof AuthenticatedDailyWrapRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFieldRoute: typeof AuthenticatedFieldRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedMyTerritoryRoute: typeof AuthenticatedMyTerritoryRoute
  AuthenticatedPlaybookRoute: typeof AuthenticatedPlaybookRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedCanvassersCanvasserIdRoute: typeof AuthenticatedCanvassersCanvasserIdRouteWithChildren
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfirmationDeskRoute: AuthenticatedConfirmationDeskRoute,
  AuthenticatedDailyWrapRoute: AuthenticatedDailyWrapRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFieldRoute: AuthenticatedFieldRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedMyTerritoryRoute: AuthenticatedMyTerritoryRoute,
  AuthenticatedPlaybookRoute: AuthenticatedPlaybookRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedCanvassersCanvasserIdRoute:
    AuthenticatedCanvassersCanvasserIdRouteWithChildren,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiInternalRotateBoardsRoute: ApiInternalRotateBoardsRoute,
  ApiPublicMondayLiveDispatchRoute: ApiPublicMondayLiveDispatchRoute,
  ApiPublicMondayWebhookRoute: ApiPublicMondayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
